formatter: "markdown"

header-from: ./.config/header.md
footer-from: ./.config/footer.md

output:
  file: ./README.md
  mode: replace
  template: |-
    {{ .Content }}

sections:
  hide:
    - header
    - footer
    - modules

settings:
  indent: 3

content: |-
  ## Account assignments
  A Terraform module which helps you assign permissions-sets to users and groups. Read [this](https://docs.aws.amazon.com/singlesignon/latest/userguide/useraccess.html) page for more information.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
