formatter: "markdown"

header-from: ./.config/header.md
footer-from: ./.config/footer.md

output:
  file: ./README.md
  mode: replace
  template: |-
    {{ .Content }}

sections:
  show:
    - header
    - footer

content: |-
  # AWS IAM Identity Center (SSO Admin) Terraform module
  A Terraform module which helps you assign permissions-sets to users and groups. Read [this](https://docs.aws.amazon.com/singlesignon/latest/userguide/what-is.html) page for more information.

  {{ .Header }}

  ## Example
  ```hcl
  {{ include "./example/main.tf" }}
  ```
  {{ include "./modules/permission-sets/README.md" }}

  {{ include "./modules/account-assignments/README.md" }}

  {{ .Footer }}
